<?php
/**
 * @file
 * Administrative UI for openlayers.
 */

/**
 * Implements hook_menu().
 */
function openlayers_ui_menu() {
  $items = array();

  // Core OpenLayers settings pages.
  $items['admin/structure/openlayers'] = array(
    'title' => 'Openlayers',
    'description' => 'Manage maps, layers, sources, controls, styles, and interactions.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_admin_settings'),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers_ui.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/structure/openlayers/settings'] = array(
    'title' => 'Settings',
    'access arguments' => array('administer openlayers'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 10,
  );

  return $items;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function openlayers_ui_ctools_plugin_directory($owner, $plugin_type) {
  return 'src/Plugin/' . str_replace("\\", DIRECTORY_SEPARATOR, $plugin_type);
}

/**
 * Implements hook_ctools_plugin_api().
 */
function openlayers_ui_ctools_plugin_api($module, $api) {
  return array(
    'version' => 1,
    'path' => drupal_get_path('module', 'openlayers_ui') . '/includes'
  );
}

/**
 * Implements hook_help().
 */
function openlayers_ui_help($path, $arg) {
  $output = NULL;

  switch ($path) {
    case 'admin/help#openlayers':
      $output = t('Openlayers is a module who displays information on a map using the <a href="@url">Openlayers library</a>.', array('@url' => 'http://ol3js.org/'));
      break;
    case 'admin/structure/openlayers':
      $output = t('Openlayers configuration and settings.');
      break;
    case 'admin/structure/openlayers/maps':
      $output = t('Manage the Openlayers maps.');
      break;
    case 'admin/structure/openlayers/projections':
      $output = t('Managing projections is not yet ready. Feel free to contribute.');
      break;
    case 'admin/structure/openlayers/styles':
      $output = t('Manage the Openlayers styles for the features displayed on maps.');
      break;
    case 'admin/structure/openlayers/layers':
      $output = t('Manage the Openlayers layers. Maps are composed of layers.');
      break;
    case 'admin/structure/openlayers/sources':
      $output = t('Manage the Openlayers sources. Layers must have a source defined.');
      break;
    case 'admin/structure/openlayers/controls':
      $output = t('Manage the Openlayers controls. Maps are composed of controls.');
      break;
    case 'admin/structure/openlayers/interactions':
      $output = t('Manage the Openlayers interactions. Maps are composed of interactions.');
      break;
    case 'admin/structure/openlayers/components':
      $output = t('Manage the custom components. These components are JS objects that are triggered after the map has been created.');
      break;
  }

  return  '<p>' . $output . '</p>';
}
