<?php
/**
 * @file
 * Openlayers views integration.
 */

/**
 * Implements hook_views_api().
 */
function openlayers_views_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'openlayers_views') . '/views',
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function openlayers_views_ctools_plugin_directory($module, $plugin) {
  return 'src/Plugin/' . $plugin;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function openlayers_views_ctools_plugin_api($module, $api) {
  return array(
    'version' => 1,
    'path' => drupal_get_path('module', 'openlayers_views') . '/includes',
  );
}

/**
 * Return all views compatible with this module.
 *
 * Uses static caching.
 *
 * @param string $style_type
 *   The style type to filter for. Valid types:
 *   - openlayers_map_views
 *   - openlayers_source_vector
 * @param bool $reset
 *   Resets the static cache.
 *
 * @return array
 *   List of views id and display names.
 */
function openalyers_views_get_views($style_type = NULL, $reset = FALSE) {
  $cache = &drupal_static(__FUNCTION__, NULL);
  // If cache isn't set yet or the cache has to be reset iterate over all views.
  if (!isset($cache) || $reset) {
    $cache = array(
      'openlayers_source_vector' => array(),
      'openlayers_map_views' => array(),
    );
    /** @var view $view */
    foreach (views_get_all_views() as $view) {
      foreach ($view->display as $display => $data) {
        $view->set_display($display);
        if ($view->display_handler->get_option('style_plugin') == 'openlayers_source_vector' && $display != 'default') {
          $cache['openlayers_source_vector'][] = array(
            $view->name,
            $display,
          );
        }
        if ($view->display_handler->get_option('style_plugin') == 'openlayers_map_views' && $display != 'default') {
          $cache['openlayers_map_views'][] = array(
            $view->name,
            $display,
          );
        }
      }
    }
  }

  // Return views of a specific type.
  if (!empty($style_type)) {
    if (isset($cache[$style_type])) {
      return $cache[$style_type];
    }
    // Type not found / invalid.
    return array();
  }
  // Return all types.
  return $cache;
}
